using System;

// used as a key into the dictionary we'll maintain in EffectTooltipSO
public enum TooltipKeyword
{
    Exhaust,
    Purge,
    Discard,
    Draw,
    Aura,
    Scry,
    Strength,
    Block,
    TemporaryStrength,

    // TODO, be able to show the card that will be generated by an effect
    Card,
    // For now..
    StarStruck,

    AttackIntent,
    DebuffIntent,
    ChargingIntent,
    EyeOfArgos,
    Retain,
    Bulwark,
    Consume,
    Invulnerable,
    Debt,
    Transform,
    EntropysBurn,
    Stinkweed,
    MabsBoon,
    MabsMight,
    ArterialBlade,
    EmbuedKnife,
    GeneratedCard,
    PermanentlyRemove,
    HiddenStrength,
    TheGoodStuff,
    Charge,
    Discharge,
    MaxBlockLost,
    Burn,
    ExtraCardsToDealNextTurn,
    GreekFire,
    NONE,
    Dagger,
    YummySnack,
    ScrumptiousSnack,
    SpiceCake,
    BasicStrategy,
    CarefulStrategy,
    AdvancedStrategy,
    DaggerPlus,
    IronSkin,
    Treegunk,
    PowerfulStature,
    Tiefvision
}
public interface ITooltipProvider
{
    TooltipViewModel GetTooltip();

}