using System;

// used as a key into the dictionary we'll maintain in EffectTooltipSO
public enum TooltipKeyword {
    Exhaust,
    Purge,
    Discard,
    Draw,
    Aura,
    Scry,
    Strength,
    Block,
    TemporaryStrength,

    // TODO, be able to show the card that will be generated by an effect
    Card,
    // For now..
    StarStruck,
    // we COULD make a separate map for the companions. I don't see why we would though
    Aborah,
    Pythia,
    Rene,
    Entropy,
    Architect

}
public interface ITooltipProvider
{
    Tooltip GetTooltip();
    
}