using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Enemy Intents are generated by enemy behaviors
// Each enemy type has an enemy behavior, which has a
// list of enemy intents it draws from at random
// Enemy brain will be stateful, choosing its intent on
// a prepare() method call, and then executing it on an invoke() method call
[CreateAssetMenu(
    fileName = "EnemyType",
    menuName = "Enemies/Enemy Type")]
public class EnemyTypeSO : ScriptableObject
{
    public int maxHealth;
    public int baseAttackDamage;
    [Space]
    public Sprite sprite;

    public EnemyBrain enemyPattern;

    public EnemyBrain belowHalfHPEnemyPattern;
    public List<InitialStatus> initialStatuses = new List<InitialStatus>();
}

[System.Serializable]
public class InitialStatus {
    public StatusEffect status;
    public int scale;
}
